name: Deploy on all

on:
  workflow_dispatch:

jobs:

  dev:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "I am running a job in the dev environment"
          
  qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "I am running a job in the qa environment"
  
  prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: qa
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "I am running a job in the prod environment"
